### ISSUE TITLE
Configurar action para deploy

### ISSUE THREAD

**Issue by arufonsekun** [ccuffs/ccuffs-hacktoberfest-monitor#1]
## Descrição
Configurar action para automatizar deploy.

**Comment by Dovyski** [comment]
Só para confirmar: a pasta `public` é a que deve ser disponibilizada na web (DocumentRoot), certo?

**Comment by arufonsekun** [comment]
Não tenho certeza, mas pra fazer o _build_ (executando `npm run build`) o diretório `dist` (que contém tudo o que há dentro de `public` ) é gerado, creio que seja esse o que precisa ser publicado.

**Comment by Dovyski** [comment]
É a pasta `dist` mesmo, não a `public`. Acabei de fazer um [novo PR](https://github.com/ccuffs/ccuffs-hacktoberfest-monitor/pull/5) para arrumar isso.

**Comment by arufonsekun** [comment]
nice, muito obrigado!!

**Comment by arufonsekun** [comment]
Tive que criar o arquivo `vue.config.js` pra funcionar de acordo (ver essa [build](https://ci.uffs.cc/ccuffs-hacktoberfest-monitor/dev/ab9d9f0746ded883b8ce9828b06c807344de8ef0/)). Como o deploy está funcionando hei de fechar essa _issue_.
